language: python
script: python setup.py bdist_wheel
python:
- '3.6'

deploy:
  - provider: pypi
    user: baiwensimi
    password: A4bSXuu
    on:
      python: 3.6
      tags: true
      branch: master