language: python
script: python setup.py bdist_wheel
python:
- '3.6'

deploy:
  - provider: pypi
    user: baiwensimi
    password: ${PYPI_PASSWD}
    distributions: "sdist bdist_wheel"
    on:
      python: 3.6
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true